[package]
name = "judge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "judge"
path = "src/main.rs"

[dependencies]
blueprint = { path = "../core" }
anyhow = "1"
clap = { workspace = true }
csv = "1"
env_logger = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
