//! PostgreSQL serialisation of a [`RedactoDump`].

use super::RedactoDump;

/// The database schema every generated statement targets.
const SCHEMA: &str = "app_redacto";

/// Quote a value as a PostgreSQL string literal.
///
/// Single quotes are always doubled. When the value contains a backslash, tab,
/// newline or carriage return, an escape-string literal `e'…'` is emitted and
/// those characters are written as `\\`, `\t`, `\n`, `\r` — this keeps every
/// `INSERT` on a single line and makes the dump independent of the server's
/// `standard_conforming_strings` setting.
///
/// The backslash escaping only applies in the `e'…'` branch: inside a plain
/// literal a backslash is already literal, so doubling it there would corrupt
/// the value.
pub fn sql_string(value: &str) -> String {
    let needs_escape = value.contains(['\\', '\t', '\n', '\r']);
    let mut out = String::with_capacity(value.len() + 8);
    if needs_escape {
        out.push('e');
    }
    out.push('\'');
    for ch in value.chars() {
        match ch {
            '\'' => out.push_str("''"),
            '\\' if needs_escape => out.push_str("\\\\"),
            '\t' if needs_escape => out.push_str("\\t"),
            '\n' if needs_escape => out.push_str("\\n"),
            '\r' if needs_escape => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
    out
}

/// Render one `INSERT` statement.
fn insert(table: &str, columns: &str, values: &[String]) -> String {
    format!(
        "INSERT INTO {SCHEMA}.{table} ({columns}) VALUES ({});\n",
        values.join(", ")
    )
}

impl RedactoDump {
    /// Serialise the dump as a PostgreSQL script.
    ///
    /// Statements are grouped per table and emitted in foreign-key dependency
    /// order (`assets`, `asset_version`, `documents`, `document_version`,
    /// `ownerships`, `relations`) inside a single transaction.
    pub fn to_sql(&self) -> String {
        let mut out = String::new();
        out.push_str("-- Generated by the Ajila forms conversion engine (Redacto target).\n");
        out.push_str("BEGIN;\n");

        out.push_str("\n-- assets\n");
        for row in &self.assets {
            out.push_str(&insert(
                "assets",
                "id, created, asset_id, asset_type",
                &[
                    sql_string(&row.id),
                    sql_string(&row.created),
                    sql_string(&row.asset_id),
                    sql_string(row.asset_type.as_str()),
                ],
            ));
        }

        out.push_str("\n-- asset_version\n");
        for row in &self.asset_versions {
            out.push_str(&insert(
                "asset_version",
                "id, created, language, version, status, content, asset_fk_id",
                &[
                    sql_string(&row.id),
                    sql_string(&row.created),
                    sql_string(&row.language),
                    row.version.to_string(),
                    sql_string(row.status.as_str()),
                    sql_string(&row.content),
                    sql_string(&row.asset_fk_id),
                ],
            ));
        }

        out.push_str("\n-- documents\n");
        for row in &self.documents {
            let configuration = serde_json::to_string(&row.configuration).unwrap_or_default();
            out.push_str(&insert(
                "documents",
                "id, created, document_id, form_path, configuration",
                &[
                    sql_string(&row.id),
                    sql_string(&row.created),
                    sql_string(&row.document_id),
                    sql_string(&row.form_path),
                    sql_string(&configuration),
                ],
            ));
        }

        out.push_str("\n-- document_version\n");
        for row in &self.document_versions {
            out.push_str(&insert(
                "document_version",
                "id, created, language, version, status, document_fk_id",
                &[
                    sql_string(&row.id),
                    sql_string(&row.created),
                    sql_string(&row.language),
                    row.version.to_string(),
                    sql_string(row.status.as_str()),
                    sql_string(&row.document_fk_id),
                ],
            ));
        }

        out.push_str("\n-- ownerships\n");
        for row in &self.ownerships {
            out.push_str(&insert(
                "ownerships",
                "id, created, owner_id, owner_type, ownership_type, object_id, object_type",
                &[
                    sql_string(&row.id),
                    sql_string(&row.created),
                    sql_string(&row.owner_id),
                    sql_string(row.owner_type.as_str()),
                    sql_string(row.ownership_type.as_str()),
                    sql_string(&row.object_id),
                    sql_string(row.object_type.as_str()),
                ],
            ));
        }

        out.push_str("\n-- relations\n");
        for row in &self.relations {
            out.push_str(&insert(
                "relations",
                "id, created, relates_to, object_id, object_type",
                &[
                    sql_string(&row.id),
                    sql_string(&row.created),
                    sql_string(&row.relates_to),
                    sql_string(&row.object_id),
                    sql_string(row.object_type.as_str()),
                ],
            ));
        }

        out.push_str("\nCOMMIT;\n");
        out
    }
}
