[application]
name = "blueprint-app"
default_platform = "web"

[web.app]
title = "Ajila Forms Conversion Engine"

[desktop]
title = "Ajila Forms Conversion Engine"

[bundle]
identifier = "com.ajila.forms-conversion-engine"
icon = ["icons/icon.icns", "icons/icon.ico", "icons/icon.png"]

[web.watcher]
reload_html = true
watch_path = ["src"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []

[web.wasm_opt]
level = "0"
