<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="../AFFragments/IBAN.xsd"/>
  <xs:include schemaLocation="../AFFragments/LetterAddress.xsd"/>
  <xs:include schemaLocation="../AFFragments/Signature.xsd"/>

  <xs:element name="form">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="überweisungsauftrag">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="überweisungsauftrag">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="RB_SEPA"/>
                    <xs:enumeration value="RB_SEPA_Echtzeitüberweisung"/>
                    <xs:enumeration value="RB_Ausland"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="kontoinhaber">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="überweisungsauftrag_zu_lasten">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="IBANumber" type="IBANumberType"/>
                          <xs:element name="LetterAddress" type="LetterAddressType"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="empfänger" type="LetterAddressType"/>
              <xs:element name="überweisungsauftrag">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Currency" type="xs:string"/>
                    <xs:element name="valuta" type="xs:string"/>
                    <xs:element name="Date" type="xs:date"/>
                    <xs:choice>
                      <xs:sequence>
                        <xs:element name="StreetNumber">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="RB_Ben"/>
                              <xs:enumeration value="RB_Our"/>
                              <xs:enumeration value="RB_Share"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:element>
                      </xs:sequence>
                    </xs:choice>
                    <xs:element name="verwendungszweck">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="unknown" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="unterschrift_en" type="SignatureType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
