<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="../AFFragments/Address.xsd"/>
  <xs:include schemaLocation="../AFFragments/Individual.xsd"/>
  <xs:include schemaLocation="../AFFragments/Signature.xsd"/>

  <xs:element name="form">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="agreement_for_the_placement_of_payment_orders_via_the_electronic_funds_transfer_eft_service">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="client">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Company" type="xs:string"/>
                    <xs:element name="authorized_representative_s">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="IndividualBasic" type="IndividualBasicType"/>
                          <xs:element name="Address" type="AddressType"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="agreement">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="StreetNumber" type="xs:string"/>
                    <xs:element name="unknown" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="signature_s">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="client" type="SignatureType"/>
                    <xs:element name="ubs_europe_se" type="SignatureType"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
