<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="../AFFragments/Signature.xsd"/>

  <xs:element name="form">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="poderes_de_representación_y_muestras_de_firmas_para">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titular_de_la_cuenta">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="razón_social" type="xs:string"/>
                    <xs:element name="IBAN" type="xs:string"/>
                    <xs:element name="Date" type="xs:date"/>
                    <xs:element name="StreetNumber" type="xs:string"/>
                    <xs:element name="unknown">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="RB_1"/>
                          <xs:enumeration value="RB_2"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:choice>
                      <xs:sequence>
                      </xs:sequence>
                      <xs:sequence>
                      </xs:sequence>
                    </xs:choice>
                    <xs:element name="poder_de_representación_frente_al_banco1" type="xs:string"/>
                    <xs:element name="Company" type="xs:string"/>
                    <xs:element name="Name" type="xs:string"/>
                    <xs:element name="apellido_nombre_s">
                      <xs:complexType>
                        <xs:sequence>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nombres_de_los_apoderados">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="unknown" type="xs:string"/>
                    <xs:element name="unknown" type="xs:string"/>
                    <xs:element name="unknown" type="xs:string"/>
                    <xs:element name="Name" type="xs:string"/>
                    <xs:element name="unknown" type="xs:string"/>
                    <xs:element name="unknown" type="xs:string"/>
                    <xs:element name="StreetNumber" type="xs:string"/>
                    <xs:element name="StreetNumber" type="xs:string"/>
                    <xs:element name="StreetNumber" type="xs:string"/>
                    <xs:element name="StreetNumber" type="xs:string"/>
                    <xs:element name="datos_de_comunicación_adicionales">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Email" type="xs:string"/>
                          <xs:element name="Email" type="xs:string"/>
                          <xs:element name="fax_oficina" type="xs:string"/>
                          <xs:element name="fax_privado" type="xs:string"/>
                          <xs:element name="Nationality">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value=""/>
                                <xs:enumeration value="Alemania"/>
                                <xs:enumeration value="Austria"/>
                                <xs:enumeration value="Bélgica"/>
                                <xs:enumeration value="Bulgaria"/>
                                <xs:enumeration value="Chipre"/>
                                <xs:enumeration value="Croacia"/>
                                <xs:enumeration value="Dinamarca"/>
                                <xs:enumeration value="Eslovaquia"/>
                                <xs:enumeration value="Eslovenia"/>
                                <xs:enumeration value="Espana"/>
                                <xs:enumeration value="Estonia"/>
                                <xs:enumeration value="Finlandia"/>
                                <xs:enumeration value="Francia"/>
                                <xs:enumeration value="Grecia"/>
                                <xs:enumeration value="Hungría"/>
                                <xs:enumeration value="Irlanda"/>
                                <xs:enumeration value="Islandia"/>
                                <xs:enumeration value="Italia"/>
                                <xs:enumeration value="Letonia"/>
                                <xs:enumeration value="Liechtenstein"/>
                                <xs:enumeration value="Lituania"/>
                                <xs:enumeration value="Luxemburgo"/>
                                <xs:enumeration value="Malta"/>
                                <xs:enumeration value="Noruega"/>
                                <xs:enumeration value="Países Bajos"/>
                                <xs:enumeration value="Polonia"/>
                                <xs:enumeration value="Portugal"/>
                                <xs:enumeration value="República Checa"/>
                                <xs:enumeration value="Rumanía"/>
                                <xs:enumeration value="Suecia"/>
                                <xs:enumeration value="Todos los países latinoamericanos"/>
                                <xs:enumeration value="&lt;Todos los demás&gt;"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="número_identificador_de_personas_físicas_nci" type="xs:string"/>
                          <xs:element name="unknown" type="xs:string"/>
                          <xs:element name="Place" type="xs:string"/>
                          <xs:element name="Date" type="xs:date"/>
                          <xs:element name="Name" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ubs_europe_se" type="SignatureType"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="anexomifid_ii_número_identificador1de_personas_físicas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nacionalidadinterne_bearbeitungsvermerke">
                <xs:complexType>
                  <xs:sequence>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="kontoinhaber">
                <xs:complexType>
                  <xs:sequence>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="legitimation_von_vertretungsberechtigten">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="vertretungsberechtigter">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="legitimation_durch_postident" type="xs:string"/>
                          <xs:element name="Street" type="xs:string"/>
                          <xs:element name="StreetNumber" type="xs:string"/>
                          <xs:element name="PostalCode" type="xs:string"/>
                          <xs:element name="ciudad" type="xs:string"/>
                          <xs:element name="unknown" type="xs:string"/>
                          <xs:element name="unknown" type="xs:string"/>
                          <xs:element name="Place" type="xs:string"/>
                          <xs:element name="Country" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ausweis">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="art_des_ausweises" type="xs:string"/>
                          <xs:element name="StreetNumber" type="xs:string"/>
                          <xs:element name="ausgestellt_von" type="xs:string"/>
                          <xs:element name="ausgestellt_am" type="xs:string"/>
                          <xs:element name="compliance_register_geprüft_cosima" type="xs:string"/>
                          <xs:element name="eine_kopie_dieses_formulars_wurde_dem_kontoinhaber_übergeben_zugesandt" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="unterschrift_en" type="SignatureType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
